# v2024.1.17
# =================================
FROM mambaorg/micromamba:1.5.6

ARG ENV_NAME

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

WORKDIR /tmp/

# Data
USER root
RUN mkdir -p /volumes/
RUN mkdir -p /volumes/input
RUN mkdir -p /volumes/output
RUN mkdir -p /volumes/database

# Retrieve VEBA repository
RUN mkdir -p veba/
USER $MAMBA_USER

# Install dependencies
RUN micromamba install -y -n base -c conda-forge -c bioconda -c jolespin git pip genopype soothsayer_utils biopython && \ 
    micromamba clean -a -y -f

# Download developmental version
COPY --chown=$MAMBA_USER:$MAMBA_USER ./CRISPRCasTyper/ CRISPRCasTyper/

# Add environment scripts to environment bin
ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN pip install CRISPRCasTyper/

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
