# v2024.2.7
# =================================
FROM mambaorg/micromamba:1.5.6

ARG ENV_NAME

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

WORKDIR /tmp/

# Data
USER root
RUN mkdir -p /volumes/
RUN mkdir -p /volumes/input
RUN mkdir -p /volumes/output
RUN mkdir -p /volumes/database

# Retrieve VEBA repository
USER $MAMBA_USER

# Install dependencies
RUN micromamba install -y -n base -c bioconda seqkit && \ 
    micromamba clean -a -y -f


ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
